# fly.toml app configuration file generated for falling-cloud-372 on 2023-05-19T07:33:47+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "falling-cloud-372"
primary_region = "ams"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
