POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNpbW9uIiwiaWQiOiI2NDc0NjE2MjUwNmE4ZDZkNmYyNjA3N2YiLCJpYXQiOjE2ODUzNTkzNzMsImV4cCI6MTY4NTM2Mjk3M30.w6mILfXmUeiZZUnCkUev-OoE6jKeIMY7yy4gWqdEGNc

{
  "title": "Brisket",
  "author": "Zuccy",
  "url": "https://www.meta.com",
  "likes": 3,
  "user": "64746162506a8d6d6f26077f"
}