DELETE http://localhost:3003/api/blogs/6478908218cc91a21c72430d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNpbW9uIiwiaWQiOiI2NDc0NjE2MjUwNmE4ZDZkNmYyNjA3N2YiLCJpYXQiOjE2ODU2MjI3MjUsImV4cCI6MTY4NTYyNjMyNX0.Y1iHlcOjafmbOD6jhCzFqDDO6iV19vk9evTMf1WsVnk

{
  "title": "Brisket",
  "author": "Zuccy",
  "url": "https://www.meta.com",
  "likes": 3,
  "user": "64746162506a8d6d6f26077f"
}