DELETE http://localhost:3003/api/blogs/6478aea830d1dce02b07781b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNpbW9uIiwiaWQiOiI2NDc0NjE2MjUwNmE4ZDZkNmYyNjA3N2YiLCJpYXQiOjE2ODU2MzAzNzQsImV4cCI6MTY4NTYzMzk3NH0.AX4S7SWpwKlXQ8XruvXDrcJc5T4xt3ggNw2BzEq0bcQ

{
  "title": "Brisket",
  "author": "Zuccy",
  "url": "https://www.meta.com",
  "likes": 3,
  "user": "64746162506a8d6d6f26077f"
}